# -*- coding: utf-8 -*-
"""Copy of colourpaletteproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQ9wGduFC7WgpzgaAnXvgW56baVVmzho
"""

import requests
import pandas as pd
import json
import matplotlib

dataset = requests.get("https://raw.githubusercontent.com/Experience-Monks/nice-color-palettes/master/1000.json") #http request to get data from api
palettes = json.loads(dataset.text) #converts it into list of palettes
palettes_select = [i for i in palettes if len(i) == 5] #selects only palettes with length = 5 colours

def hex_to_rgb(hex_value): #will convert hex values to RGB and normalize the new values between 0-1 to be used in NN
  hex_value = hex_value.lstrip("#") #removes '#' from hex values
  if len(hex_value) != 6: # Check if the hex_value has 6 characters
    return None
  try: #deals with potential errors during conversion
    return tuple(round(int(hex_value[i*2:i*2+2], 16)/255, 2) for i in range(3)) # Creates a tuple with each pair of hex converted to RGB and normalized, values rounded to 2 decimals
  except ValueError: #deals with cases wiht invalid hex characters
    return None

palettes_rgb = []

for palette in palettes_select:
  rgb_value = []
  for colour in palette:
    rgb = hex_to_rgb(colour)
    if rgb is not None: # Check if rgb is not None before appending
      rgb_value.append(rgb)
  palettes_rgb.append(rgb_value)



print (palettes_rgb[0])

